name: release fabric
on:
  push:
    tags:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      # Example: 1.0.0-MC1.21-fabric
      - "[0-9]+.[0-9]+.[0-9]+-MC[0-9]+.[0-9]+.[0-9x]+-fabric"

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Split tag name
        env:
          TAG: ${{ github.ref_name }}
        id: versions
        run: |
          echo "::set-output name=modversion::${TAG%%-*}"
          echo "::set-output name=mcversion::${${TAG%-*}#*-MC}"

      - name: Setup Gradle
        with:
          cache-read-only: true
          add-job-summary-as-pr-comment: on-failure
        uses: gradle/actions/setup-gradle@v3

      - name: Execute build
        run: ./gradlew build

      - name: Publish (curseforge, modrinth, github) # https://github.com/Kir-Antipov/mc-publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: TODO
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: TODO
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-tag: ${{ steps.build.outputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadoc).jar

          name: HorsStatsMod ${{ steps.versions.outputs.modversion }} for Minecraft ${{ steps.versions.outputs.mcversion }}
          version: ${{ steps.versions.outputs.modversion }}
          version-type: release
          changelog-file: CHANGELOG.md
          java: |
            21

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
